// Detay paneller için örnek data kullanımları
// eslint-disable-next-line no-unused-vars
var cycleInstructionItems = [
  {
    type: 'Autocomplete',
    inputType: null,
    modelProperty: 'EmployeeId',
    parentProperty: null,
    labelProperty: 'Description1',
    url: 'VisionNextEmployee/api/Employee/AutoCompleteSearch',
    label: this.$t('insert.CycleInstruction.Employee'),
    required: true,
    disabled: false,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: null,
    id: 1,
    defaultValue: null,
    objectKey: null // update için kullanılır
  },
  {
    type: 'Dropdown',
    inputType: null,
    modelProperty: 'CustomerId',
    parentProperty: null,
    labelProperty: 'Description1',
    url: 'VisionNextCustomer/api/Customer/Search',
    label: this.$t('insert.CycleInstruction.Customer'),
    required: true,
    disabled: false,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: null,
    id: 12,
    defaultValue: null,
    objectKey: null // update için kullanılır
  },
  {
    type: 'Dropdown',
    inputType: null,
    modelProperty: 'CustomerLocationId',
    parentProperty: 'RecordId',
    labelProperty: 'Description1',
    request: '{"AndConditionModel": {"CustomerIds":[val]}}',
    url: 'VisionNextCustomer/api/CustomerLocation/Search',
    label: this.$t('insert.CycleInstruction.CustomerLocation'),
    required: true,
    disabled: false,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: 1,
    id: 2,
    defaultValue: null,
    objectKey: null // update için kullanılır
  },
  {
    type: 'Lookup',
    inputType: null,
    modelProperty: 'CustomeLocationId',
    parentProperty: null,
    labelProperty: 'Description1',
    url: 'CUSTOMER_CATEGORY_3',
    label: this.$t('insert.CycleInstruction.CustomerLookup'),
    required: true,
    disabled: false,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: null,
    id: 123,
    defaultValue: null,
    objectKey: null // update için kullanılır
  },
  {
    type: 'Label',
    inputType: 'text',
    modelProperty: 'EmployeeDesc11',
    parentProperty: 'Description1',
    labelProperty: 'Description1',
    url: null,
    label: this.$t('insert.CycleInstruction.EmployeeDesc11'),
    required: false,
    disabled: true,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: 1,
    id: null,
    defaultValue: null,
    objectKey: null // update için kullanılır
  },
  {
    type: 'Label',
    inputType: 'text',
    modelProperty: 'BranchDesc11',
    parentProperty: 'BranchId',
    labelProperty: 'Description1',
    url: 'VisionNextBranch/api/Branch/Get',
    label: this.$t('insert.CycleInstruction.BranchDesc11'),
    required: false,
    disabled: true,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: 1,
    id: null,
    defaultValue: null,
    objectKey: null // update için kullanılır
  },
  {
    type: 'Text',
    inputType: 'number',
    modelProperty: 'Amount',
    parentProperty: null,
    labelProperty: 'Description1',
    url: null,
    label: this.$t('insert.CycleInstruction.Amount'),
    required: true,
    disabled: false,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: null,
    id: 2,
    defaultValue: null,
    objectKey: null // update için kullanılır
  },
  {
    type: 'Text',
    inputType: 'text',
    modelProperty: 'Code',
    parentProperty: 'Code',
    labelProperty: 'Description1',
    url: null,
    label: this.$t('insert.CycleInstruction.Code'),
    required: true,
    disabled: false,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: 1,
    id: null,
    defaultValue: null,
    objectKey: null // update için kullanılır
  },
  {
    type: 'Check',
    inputType: null,
    modelProperty: 'StatusId',
    parentProperty: null,
    labelProperty: 'Description1',
    url: null,
    label: this.$t('insert.CycleInstruction.Check'),
    required: true,
    disabled: false,
    visible: true,
    hideOnTable: true,
    isUnique: false,
    parentId: null,
    id: 3,
    defaultValue: null,
    objectKey: null // update için kullanılır
  }
]
